Homework 1

In [9]:
import numpy as np

In [10]:
np.__version__

'1.18.5'

In [12]:
import pandas as pd

In [8]:
pandas.__version__

'1.0.5'

In [11]:
!wget https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv

--2021-09-13 00:14:30--  https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.111.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1475504 (1.4M) [text/plain]
Saving to: ‘data.csv’

data.csv            100%[===================>]   1.41M   949KB/s    in 1.5s    

2021-09-13 00:14:32 (949 KB/s) - ‘data.csv’ saved [1475504/1475504]



In [109]:
data_file = pd.read_csv("data.csv")
print(data_file)

          Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driv

In [39]:
df = data_file[data_file['Make'] == 'BMW']
print(df)

      Make       Model  Year             Engine Fuel Type  Engine HP  \
0      BMW  1 Series M  2011  premium unleaded (required)      335.0   
1      BMW    1 Series  2011  premium unleaded (required)      300.0   
2      BMW    1 Series  2011  premium unleaded (required)      300.0   
3      BMW    1 Series  2011  premium unleaded (required)      230.0   
4      BMW    1 Series  2011  premium unleaded (required)      230.0   
...    ...         ...   ...                          ...        ...   
11901  BMW          Z4  2016  premium unleaded (required)      240.0   
11902  BMW          Z4  2016  premium unleaded (required)      335.0   
11903  BMW          Z8  2001  premium unleaded (required)      394.0   
11904  BMW          Z8  2002  premium unleaded (required)      394.0   
11905  BMW          Z8  2003  premium unleaded (required)      394.0   

       Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL  rear wheel d

In [40]:
df['MSRP'].mean()

61546.76347305389

In [65]:
df = data_file[(data_file['Year'] > 2014) & (data_file['Engine HP'].isnull())]

In [68]:
df

Make        Model  Year                  Engine Fuel Type  \
539            FIAT         500e  2015                          electric   
540            FIAT         500e  2016                          electric   
541            FIAT         500e  2017                          electric   
2905        Lincoln  Continental  2017    premium unleaded (recommended)   
2906        Lincoln  Continental  2017    premium unleaded (recommended)   
2907        Lincoln  Continental  2017    premium unleaded (recommended)   
2908        Lincoln  Continental  2017    premium unleaded (recommended)   
4203           Ford       Escape  2017                  regular unleaded   
4204           Ford       Escape  2017                  regular unleaded   
4205           Ford       Escape  2017                  regular unleaded   
4206           Ford       Escape  2017                  regular unleaded   
4785           Ford        Focus  2015                          electric   
4789           Ford        Focus  2016                          electric   
4798           Ford        Focus  2017                          electric   
5825      Chevrolet       Impala  2015  flex-fuel (unleaded/natural gas)   
5830      Chevrolet       Impala  2015  flex-fuel (unleaded/natural gas)   
5831      Chevrolet       Impala  2016  flex-fuel (unleaded/natural gas)   
5833      Chevrolet       Impala  2016  flex-fuel (unleaded/natural gas)   
5839      Chevrolet       Impala  2017  flex-fuel (unleaded/natural gas)   
5840      Chevrolet       Impala  2017  flex-fuel (unleaded/natural gas)   
6388         Nissan         Leaf  2015                          electric   
6389         Nissan         Leaf  2015                          electric   
6390         Nissan         Leaf  2015                          electric   
6391         Nissan         Leaf  2015                          electric   
6392         Nissan         Leaf  2016                          electric   
6393         Nissan         Leaf  2016                          electric   
6394         Nissan         Leaf  2016                          electric   
6578  Mercedes-Benz      M-Class  2015                            diesel   
6908        Lincoln          MKZ  2017                  regular unleaded   
6910        Lincoln          MKZ  2017                  regular unleaded   
6916        Lincoln          MKZ  2017                  regular unleaded   
6918        Lincoln          MKZ  2017                  regular unleaded   
6925          Tesla      Model S  2015                          electric   
6926          Tesla      Model S  2015                          electric   
6927          Tesla      Model S  2015                          electric   
6928          Tesla      Model S  2015                          electric   
6929          Tesla      Model S  2015                          electric   
6930          Tesla      Model S  2016                          electric   
6931          Tesla      Model S  2016                          electric   
6932          Tesla      Model S  2016                          electric   
6933          Tesla      Model S  2016                          electric   
6934          Tesla      Model S  2016                          electric   
6935          Tesla      Model S  2016                          electric   
6936          Tesla      Model S  2016                          electric   
6937          Tesla      Model S  2016                          electric   
6938          Tesla      Model S  2016                          electric   
9850            Kia      Soul EV  2015                          electric   
9851            Kia      Soul EV  2015                          electric   
9852            Kia      Soul EV  2016                          electric   
9853            Kia      Soul EV  2016                          electric   
9854            Kia      Soul EV  2016                          electric   

      Engine HP  Engine Cylinders Transmission Type      Drive

In [74]:
num_r=df.shape[0]

In [75]:
num_r

51

In [87]:
data_file.mean()

Year                 2010.384338
Engine HP             249.386070
Engine Cylinders        5.628829
Number of Doors         3.436093
highway MPG            26.637485
city mpg               19.733255
Popularity           1554.911197
MSRP                40594.737032
dtype: float64

In [88]:
data_file.fillna(0)

Make       Model  Year                Engine Fuel Type  Engine HP  \
0          BMW  1 Series M  2011     premium unleaded (required)      335.0   
1          BMW    1 Series  2011     premium unleaded (required)      300.0   
2          BMW    1 Series  2011     premium unleaded (required)      300.0   
3          BMW    1 Series  2011     premium unleaded (required)      230.0   
4          BMW    1 Series  2011     premium unleaded (required)      230.0   
...        ...         ...   ...                             ...        ...   
11909    Acura         ZDX  2012     premium unleaded (required)      300.0   
11910    Acura         ZDX  2012     premium unleaded (required)      300.0   
11911    Acura         ZDX  2012     premium unleaded (required)      300.0   
11912    Acura         ZDX  2013  premium unleaded (recommended)      300.0   
11913  Lincoln      Zephyr  2006                regular unleaded      221.0   

       Engine Cylinders Transmission Type      Driven_Wheels  Number of Doors  \
0                   6.0            MANUAL   rear wheel drive              2.0   
1                   6.0            MANUAL   rear wheel drive              2.0   
2                   6.0            MANUAL   rear wheel drive              2.0   
3                   6.0            MANUAL   rear wheel drive              2.0   
4                   6.0            MANUAL   rear wheel drive              2.0   
...                 ...               ...                ...              ...   
11909               6.0         AUTOMATIC    all wheel drive              4.0   
11910               6.0         AUTOMATIC    all wheel drive              4.0   
11911               6.0         AUTOMATIC    all wheel drive              4.0   
11912               6.0         AUTOMATIC    all wheel drive              4.0   
11913               6.0         AUTOMATIC  front wheel drive              4.0   

                             Market Category Vehicle Size  Vehicle Style  \
0      Factory Tuner,Luxury,High-Performance      Compact          Coupe   
1                         Luxury,Performance      Compact    Convertible   
2                    Luxury,High-Performance      Compact          Coupe   
3                         Luxury,Performance      Compact          Coupe   
4                                     Luxury      Compact    Convertible   
...                                      ...          ...            ...   
11909             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11910             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11911             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11912             Crossover,Hatchback,Luxury      Midsize  4dr Hatchback   
11913                                 Luxury      Midsize          Sedan   

       highway MPG  city mpg  Popularity   MSRP  
0               26        19        3916  46135  
1               28        19        3916  40650  
2               28        20        3916  36350  
3               28        18        3916  29450  
4               28        18        3916  34500  
...            ...       ...         ...    ...  
11909           23        16         204  46120  
11910           23        16         204  56670  
11911           23        16         204  50620  
11912           23        16         204  50920  
11913           26        17          61  28995  

[11914 rows x 16 columns]

In [90]:

data_file.fillna(0).mean()

Year                 2010.384338
Engine HP             247.941749
Engine Cylinders        5.614655
Number of Doors         3.434363
highway MPG            26.637485
city mpg               19.733255
Popularity           1554.911197
MSRP                40594.737032
dtype: float64

Sum of elements of the inverse matrix 
Select all the "Rolls-Royce" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
What's the sum of all the elements of the result?
Hint: if the result is negative, re-read the task one more time

In [100]:
q7 = data_file[['Make', 'Engine HP', 'Engine Cylinders', 'highway MPG'] ]

In [101]:
q7

Make  Engine HP  Engine Cylinders  highway MPG
0          BMW      335.0               6.0           26
1          BMW      300.0               6.0           28
2          BMW      300.0               6.0           28
3          BMW      230.0               6.0           28
4          BMW      230.0               6.0           28
...        ...        ...               ...          ...
11909    Acura      300.0               6.0           23
11910    Acura      300.0               6.0           23
11911    Acura      300.0               6.0           23
11912    Acura      300.0               6.0           23
11913  Lincoln      221.0               6.0           26

[11914 rows x 4 columns]

In [133]:
q7 = data_file[data_file['Make'] == 'Rolls-Royce']

In [134]:
q7 = q7[['Engine HP', 'Engine Cylinders', 'highway MPG']]

In [135]:
q7

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5276       563.0              12.0           21
5277       563.0              12.0           21
5278       563.0              12.0           21
5279       563.0              12.0           20
5280       563.0              12.0           20
5281       563.0              12.0           21
5282       563.0              12.0           21
5283       563.0              12.0           21
5284       563.0              12.0           21
7443       322.0              12.0           15
7444       322.0              12.0           15
7553       453.0              12.0           19
7554       453.0              12.0           19
7555       453.0              12.0           19
7556       453.0              12.0           19
7557       453.0              12.0           19
7558       453.0              12.0           19
7559       453.0              12.0           19
7560       453.0              12.0           19
7561       453.0              12.0           19
7562       453.0              12.0           19
7563       453.0              12.0           19
7564       453.0              12.0           19
9431       322.0              12.0           15
9432       322.0              12.0           15
11448      624.0              12.0           21
11449      624.0              12.0           21
11450      624.0              12.0           21

In [141]:
q7 = q7.drop_duplicates()
q7

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

In [143]:
q7t = q7.T

In [146]:
q7t

2921   3505   5275   5279   7443   7553   11448
Engine HP         325.0  563.0  563.0  563.0  322.0  453.0  624.0
Engine Cylinders    8.0   12.0   12.0   12.0   12.0   12.0   12.0
highway MPG        15.0   19.0   21.0   20.0   15.0   19.0   21.0

In [159]:
npq7 = np.array(q7)

In [160]:
npq7

array([[325.,   8.,  15.],
       [563.,  12.,  19.],
       [563.,  12.,  21.],
       [563.,  12.,  20.],
       [322.,  12.,  15.],
       [453.,  12.,  19.],
       [624.,  12.,  21.]])

In [161]:
npT = npq7.T

In [168]:
xtx = npT.dot(npq7)

In [169]:
xtx

array([[1.754801e+06, 3.965600e+04, 6.519600e+04],
       [3.965600e+04, 9.280000e+02, 1.500000e+03],
       [6.519600e+04, 1.500000e+03, 2.454000e+03]])

In [170]:
inverseXTX = np.linalg.inv(xtx)

In [166]:
inverseXTX

array([[ 2.26655979e+10,  1.31639849e+11,  6.00619990e+10,
         6.00514968e+09, -3.30011828e+10, -2.43060764e+10,
        -1.55510137e+11],
       [-3.27415886e+14, -1.81277359e+15, -1.62961971e+15,
         6.77449931e+14,  1.21383250e+14,  9.46190933e+14,
         1.91564644e+15],
       [ 3.76975783e+15,  1.38681644e+16,  6.30933989e+15,
        -7.54480926e+15, -1.37638987e+15, -4.08171120e+15,
        -9.68776581e+15],
       [ 1.92477705e+15,  5.61962212e+15,  2.10780469e+15,
        -3.28629886e+15, -3.28648700e+14, -2.02813806e+15,
        -3.36752589e+15],
       [ 1.03705184e+15,  4.30192234e+15,  2.42889709e+15,
        -2.15278424e+15, -4.23061002e+14, -1.43782129e+15,
        -3.40852079e+15],
       [-3.74611682e+15, -1.39027387e+16, -6.71094389e+15,
         7.42405523e+15,  1.31210760e+15,  4.38132983e+15,
         9.99360111e+15],
       [-2.65806912e+15, -8.07428433e+15, -2.50551812e+15,
         4.88238320e+15,  6.94630722e+14,  2.22016600e+15,
         4.5546686

In [175]:
inverseXTX.sum()

0.032212320677486195

In [181]:
y = np.array([1000, 1100, 900, 1200, 1000, 850, 1300])

In [178]:
y

array([1000, 1100,  900, 1200, 1000,  850, 1300])

In [182]:
inverseXTX.shape

(3, 3)

Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?.

In [184]:
npT.shape

(3, 7)

In [185]:
res = inverseXTX.dot(npT)

In [186]:
res

array([[-0.00486592,  0.00336507, -0.00049461,  0.00143523, -0.00139492,
        -0.0023309 ,  0.00266407],
       [-0.19020088,  0.09362543, -0.08379139,  0.00491702,  0.22997159,
        -0.00609915, -0.02848958],
       [ 0.25164625, -0.13888652,  0.0729151 , -0.03298571, -0.09739786,
         0.07339609, -0.04480526]])

In [187]:
res.shape

(3, 7)

In [188]:
y.shape

(7,)

In [189]:
w = res.dot(y)

In [190]:
w[0]

0.19989598183186175